import { ContentResult, ProductResult, SearchHistoryItem } from "./types";

export const TRENDING_SEARCHES = [
  "that chicken on a tree video",
  "cozy dorm fairy lights",
  "cat jumping into pool",
  "sped up lovee meee",
  "slow sunday morning coffee",
];

export const MOCK_RESULTS: ContentResult[] = [
  {
    content_id: "1",
    platform: "tiktok",
    url: "https://tiktok.com/@vibes/1",
    creator: "cozygirl",
    caption: "the coziest dorm room transformation you've ever seen ✨ fairy lights and good vibes only",
    thumb: "https://picsum.photos/seed/cozy1/400/530",
    video_url: "",
    likes: 245000,
    views: 1800000,
    comments: 3200,
    score: 0.97,
  },
  {
    content_id: "2",
    platform: "instagram",
    url: "https://instagram.com/p/2",
    creator: "aestheticroom",
    caption: "Sunday reset 🌿 new sheets, clean desk, fresh start",
    thumb: "https://picsum.photos/seed/room2/400/530",
    video_url: "",
    likes: 89000,
    views: 420000,
    comments: 1100,
    score: 0.94,
  },
  {
    content_id: "3",
    platform: "tiktok",
    url: "https://tiktok.com/@vibes/3",
    creator: "studywithme",
    caption: "3 hour study session in the library with rain sounds 🌧📚",
    thumb: "https://picsum.photos/seed/study3/400/530",
    video_url: "",
    likes: 512000,
    views: 3200000,
    comments: 4500,
    score: 0.91,
  },
  {
    content_id: "4",
    platform: "instagram",
    url: "https://instagram.com/p/4",
    creator: "plantmom",
    caption: "my monstera finally put out a new leaf after 3 months 😭🌱",
    thumb: "https://picsum.photos/seed/plant4/400/530",
    video_url: "",
    likes: 67000,
    views: 310000,
    comments: 890,
    score: 0.88,
  },
  {
    content_id: "5",
    platform: "tiktok",
    url: "https://tiktok.com/@vibes/5",
    creator: "cafehop",
    caption: "found the cutest hidden café in austin — matcha was unreal",
    thumb: "https://picsum.photos/seed/cafe5/400/530",
    video_url: "",
    likes: 178000,
    views: 950000,
    comments: 2100,
    score: 0.85,
  },
  {
    content_id: "6",
    platform: "tiktok",
    url: "https://tiktok.com/@vibes/6",
    creator: "sunsetvibes",
    caption: "golden hour hits different on this rooftop 🌅",
    thumb: "https://picsum.photos/seed/sunset6/400/530",
    video_url: "",
    likes: 334000,
    views: 2100000,
    comments: 5600,
    score: 0.82,
  },
  {
    content_id: "7",
    platform: "instagram",
    url: "https://instagram.com/p/7",
    creator: "thriftfinds",
    caption: "scored this vintage jacket for $8 at goodwill — I'm screaming",
    thumb: "https://picsum.photos/seed/thrift7/400/530",
    video_url: "",
    likes: 92000,
    views: 480000,
    comments: 1300,
    score: 0.79,
  },
  {
    content_id: "8",
    platform: "tiktok",
    url: "https://tiktok.com/@vibes/8",
    creator: "catcontent",
    caption: "he really just jumped into the pool like it was nothing 😂🐱",
    thumb: "https://picsum.photos/seed/cat8/400/530",
    video_url: "",
    likes: 890000,
    views: 5400000,
    comments: 12000,
    score: 0.76,
  },
  {
    content_id: "9",
    platform: "instagram",
    url: "https://instagram.com/p/9",
    creator: "minimalkitchen",
    caption: "the perfect morning: french press, sourdough, and silence",
    thumb: "https://picsum.photos/seed/kitchen9/400/530",
    video_url: "",
    likes: 156000,
    views: 720000,
    comments: 2800,
    score: 0.73,
  },
  {
    content_id: "10",
    platform: "tiktok",
    url: "https://tiktok.com/@vibes/10",
    creator: "diyqueen",
    caption: "painted my bedroom door to look like a bookshelf 📚 turned out insane",
    thumb: "https://picsum.photos/seed/diy10/400/530",
    video_url: "",
    likes: 445000,
    views: 2800000,
    comments: 6700,
    score: 0.70,
  },
  {
    content_id: "11",
    platform: "instagram",
    url: "https://instagram.com/p/11",
    creator: "traveldiary",
    caption: "this tiny village in portugal was not on the itinerary but wow",
    thumb: "https://picsum.photos/seed/travel11/400/530",
    video_url: "",
    likes: 203000,
    views: 1100000,
    comments: 3400,
    score: 0.67,
  },
  {
    content_id: "12",
    platform: "tiktok",
    url: "https://tiktok.com/@vibes/12",
    creator: "nightowl",
    caption: "2am coding session with lo-fi beats 🎵💻 the grind never stops",
    thumb: "https://picsum.photos/seed/code12/400/530",
    video_url: "",
    likes: 127000,
    views: 680000,
    comments: 1900,
    score: 0.64,
  },
];

export const MOCK_PRODUCTS: ProductResult[] = [
  {
    id: "p1",
    name: "Warm White LED Fairy Lights, 100ft",
    price: "$12.99",
    source: "Amazon",
    imageURL: "https://picsum.photos/seed/prod1/200/200",
    productURL: "#",
    groupName: "Lighting",
  },
  {
    id: "p2",
    name: "Boho Macramé Wall Hanging",
    price: "$24.50",
    source: "Etsy",
    imageURL: "https://picsum.photos/seed/prod2/200/200",
    productURL: "#",
    groupName: "Decor",
  },
  {
    id: "p3",
    name: "Minimalist Desk Organizer — Walnut",
    price: "$34.00",
    source: "Amazon",
    imageURL: "https://picsum.photos/seed/prod3/200/200",
    productURL: "#",
    groupName: "Organization",
  },
  {
    id: "p4",
    name: "Vintage Ceramic Coffee Mug Set",
    price: "$19.99",
    source: "Target",
    imageURL: "https://picsum.photos/seed/prod4/200/200",
    productURL: "#",
    groupName: "Kitchen",
  },
];

export const MOCK_HISTORY: SearchHistoryItem[] = [
  {
    id: "h1",
    query: "cozy dorm fairy lights",
    attachments: [],
    results: MOCK_RESULTS.slice(0, 4),
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "h2",
    query: "lovee meee sped up",
    attachments: [],
    results: MOCK_RESULTS.slice(2, 6),
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "h3",
    query: "cat pool video",
    attachments: [],
    results: MOCK_RESULTS.slice(5, 9),
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
];

export const RELATED_CONTENT = MOCK_RESULTS.slice(0, 6);

export const LOADING_STEPS = [
  "Embedding your query",
  "Searching indexed posts",
  "Ranking by vibe similarity",
  "Preparing results",
];

export const PLACEHOLDER_MESSAGES = [
  "Describe it in your own words...",
  "Drop an image of what you saw...",
  "Hum the melody, we'll find it...",
  "Record a video to search visually...",
  "Snap a photo to find the source...",
  "Reenact the sound or scene...",
];
